# Generated by Django 2.0.3 on 2018-04-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180401_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='poop',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
