# Generated by Django 2.0.3 on 2018-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_donorprofile_poop'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='poop',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
