# Generated by Django 2.0.3 on 2018-04-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_donorprofile_poop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='poop',
        ),
    ]
